"use client";
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import { ThemeProvider } from '@mui/material/styles';


// IMPORTING THEME 
import theme from "./theme.jsx"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}





export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider theme={theme}>
        <Navbar />
          {children}
        <Footer />
       </ThemeProvider>
      </body>
    </html>
  )
}
